# 1. Impoting Pandas

In [15]:
import pandas as pd

# Opening with local csv File

In [16]:
df = pd.read_csv('placement.csv')

In [17]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

# 3. Opening a csv file from URl

In [18]:
import requests
import pandas as pd
from io import StringIO  # Corrected from StringIo to StringIO

url = "https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}  # Fixed string literal

req = requests.get(url, headers=headers)
data = StringIO(req.text)
pd.read_csv(data)  # Corrected from pd. read_sv to pd.read_csv

,John,Doe,120 jefferson st.,Riverside,NJ,08075
0,Jack,McGinnis,220 hobo Av.,Phila,PA,9119
1,"John ""Da Man""",Repici,120 Jefferson St.,Riverside,NJ,8075
2,Stephen,Tyler,"7452 Terrace ""At the Plaza"" road",SomeTown,SD,91234
3,NaN,Blankman,NaN,SomeTown,SD,298
4,"Joan ""the bone"", Anne",Jet,"9th, at Terrace plc",Desert City,CO,123

# 4. Sep Parameter

In [29]:
pd.read_csv('practice_data.tsv', sep = '\t') #names=['s.no','Full_name','Dep','salaries']) # we can read as csv by using sep = '\t'
# If column not define we can use name.

   id     name department  salary
0   1    Alice         HR   40000
1   2      Bob         IT   55000
2   3  Charlie    Finance   60000
3   4    David         IT   52000
4   5      Eva         HR   45000